name: Deploy to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Create .env file
        run: |
          echo "PORT=3000" > app/.env
          echo "FIRECRAWL_API_KEY=${{ secrets.FIRECRAWL_API_KEY }}" >> app/.env
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> app/.env
          echo "DEFAULT_BIO_TONE=professional" >> app/.env
          echo "DEFAULT_BIO_MAX_LENGTH=500" >> app/.env
          echo "DEFAULT_BIO_NAME=Jacob Edgar-Anderson" >> app/.env
          
      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "app/,.github/"
          target: "/opt/itwasjacob/makerpass/"
          
      - name: SSH and restart
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Navigate to application directory
            cd /opt/itwasjacob/makerpass/app
            
            # Restart the application
            docker compose down
            docker compose up -d --build
            
            # Log the deployment
            echo "Deployed commit $(git rev-parse --short HEAD) at $(date)" >> /var/log/deploy.log 